# Codecov configuration
# See: https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
        branches:
          - main
          - develop
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "test/**/*"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "scripts/**/*"
  - "benchmark/**/*"
  - "**/node_modules/**"