version: '3.8'

services:
  # Development environment
  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=true
    ports:
      - "3000:3000"
    command: npm run dev

  # Test environment
  test:
    build:
      context: .
      target: testing
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    command: npm run test:ci

  # Production build
  build:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    command: node cli.mjs --version

  # Linting service
  lint:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run lint

  # Type checking service
  typecheck:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run typecheck

  # Documentation service
  docs:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: npm run docs:serve

volumes:
  node_modules: