name: Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[DOCS]: "
labels: ["documentation", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the SwissKnife documentation!
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Error or inaccuracy
        - Missing information
        - Unclear explanation
        - Outdated content
        - Formatting/structure issue
        - Other
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation you're referring to? Provide links or file paths.
      placeholder: e.g., /docs/CICD.md or URL
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe the issue with the documentation.
      placeholder: The documentation incorrectly states that... / The documentation is missing information about...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve the documentation?
      placeholder: I suggest changing/adding...
    validations:
      required: false
  - type: checkboxes
    id: contribution
    attributes:
      label: Would you be willing to contribute?
      description: Are you interested in helping fix this documentation issue?
      options:
        - label: I'd be willing to submit a PR with these changes
          required: false