name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like SwissKnife to be able to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've thought about implementing this by...
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: This feature would be useful in scenarios like...
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Perceived Priority
      description: How important do you think this feature is?
      options:
        - Critical (blocker for my usage)
        - High (significantly impacts my workflow)
        - Medium (would improve my experience)
        - Low (nice to have)
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Would you be willing to contribute?
      description: Are you interested in helping implement this feature?
      options:
        - label: I'd be willing to work on a PR for this feature
          required: false